### PR TITLE
Various improvements for Nim including commands

### PR DESCRIPTION
**Pull request by nanoant**
This set of commits improves Nim bundle. I have started recently playing with Nim and I think the bundle deserved some polish.

Just a quick demonstration on syntax highlighting with these changes:

zrzut ekranu 2015-04-14 o 23 00 04

### CODE REVIEW

**Comment by infininight** [comment]
Comments on a couple commits:

9e03dbe26bb3afa28a551756dcfab848c06df589: You scope whitespace as well as the `*` character as `keyword.control.export`, due to the way word selection in TextMate works we never want to scope whitespace as one of the 'main' scopes as it will end up getting made part of a 'word'.

795695f40897cf2c608df6dce6b0c54af18fc97b: TextMate uses Oniguruma/Onigmo which is a unicode aware reggae library, this means using \w matches a whole lot more than `[a-zA-Z]` as you suggest. Looking at [the spec](http://nim-lang.org/manual.html#identifiers-keywords) it actually only supports a very narrow set of characters. Larger that was defined but still much tighter than `\w`.

Otherwise looks good.

**Comment by nanoant** [comment]
795695f: actually [the spec's](http://nim-lang.org/manual.html#identifiers-keywords) `'\x80'..'\xff'` makes letter to be any non-ASCII (non single byte UTF8), so `\w` is actually is tighter.

9e03dbe: you are right, this deserves fixup... incoming ;)

**Comment by nanoant** [comment]
@infininight Hey, give me a shot if there anything more that deserves some edit.

**Comment by infininight** [comment]
Sorry for the delay, had hoped to get this done before I left for the weekend. Want to look at possibly improving the identifier matches but didn't get time to test it out before I left. Will look at it first thing next week.

**Pull request merged**
